// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SzerszamKolcsonzo.Data;

#nullable disable

namespace SzerszamKolcsonzo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251104203809_AddKepUrlToEszkozAndKategoria")]
    partial class AddKepUrlToEszkozAndKategoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SzerszamKolcsonzo.Models.Eszkoz", b =>
                {
                    b.Property<int>("EszkozID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EszkozID"));

                    b.Property<DateTime>("BeszerzesiDatum")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KategoriaID")
                        .HasColumnType("int");

                    b.Property<string>("KepUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("KiadasiAr")
                        .HasColumnType("int");

                    b.Property<string>("Leiras")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Vetelar")
                        .HasColumnType("int");

                    b.HasKey("EszkozID");

                    b.HasIndex("KategoriaID");

                    b.ToTable("Eszkozok");

                    b.HasData(
                        new
                        {
                            EszkozID = 1,
                            BeszerzesiDatum = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KategoriaID = 1,
                            KiadasiAr = 1500,
                            Leiras = "18V-os akkus csavarbehajtó, 2 akkuval",
                            Nev = "parkside x20 csavarbehajtó",
                            Status = 0,
                            Vetelar = 19990
                        },
                        new
                        {
                            EszkozID = 2,
                            BeszerzesiDatum = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KategoriaID = 1,
                            KiadasiAr = 1500,
                            Leiras = "230mm koronggal, 2200W teljesítmény",
                            Nev = "einhell sarokcsiszoló",
                            Status = 0,
                            Vetelar = 23000
                        },
                        new
                        {
                            EszkozID = 3,
                            BeszerzesiDatum = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KategoriaID = 2,
                            KiadasiAr = 2000,
                            Leiras = "Festékvastagság mérésére alkalmas digitális műszer",
                            Nev = "rétegvastagságmérő",
                            Status = 0,
                            Vetelar = 43500
                        },
                        new
                        {
                            EszkozID = 4,
                            BeszerzesiDatum = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KategoriaID = 2,
                            KiadasiAr = 5000,
                            Leiras = "Érintésmentes hőmérsékletmérő -50 és 800°C között",
                            Nev = "infra hőmérő",
                            Status = 0,
                            Vetelar = 87999
                        },
                        new
                        {
                            EszkozID = 5,
                            BeszerzesiDatum = new DateTime(2023, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KategoriaID = 3,
                            KiadasiAr = 500,
                            Leiras = "Összecsukható fa sörpad garnitúra",
                            Nev = "sörpad",
                            Status = 0,
                            Vetelar = 35000
                        },
                        new
                        {
                            EszkozID = 6,
                            BeszerzesiDatum = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KategoriaID = 3,
                            KiadasiAr = 500,
                            Leiras = "Háromlábú bográcsállvány, állítható lánccal",
                            Nev = "bográcsállvány",
                            Status = 0,
                            Vetelar = 17000
                        });
                });

            modelBuilder.Entity("SzerszamKolcsonzo.Models.Foglalas", b =>
                {
                    b.Property<int>("FoglalasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FoglalasID"));

                    b.Property<int>("Bevetel")
                        .HasColumnType("int");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("EszkozID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FoglalasKezdete")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FoglalasVege")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LetrehozasDatum")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("OraSzam")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Telefonszam")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("FoglalasID");

                    b.HasIndex("EszkozID");

                    b.ToTable("Foglalasok");

                    b.HasData(
                        new
                        {
                            FoglalasID = 1,
                            Bevetel = 15000,
                            Cim = "Budapest, Fő utca 1.",
                            Email = "kovacs.janos@example.com",
                            EszkozID = 1,
                            FoglalasKezdete = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            FoglalasVege = new DateTime(2025, 1, 10, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            LetrehozasDatum = new DateTime(2025, 1, 9, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Nev = "Kovács János",
                            OraSzam = 10,
                            Status = 1,
                            Telefonszam = "+36301234567"
                        },
                        new
                        {
                            FoglalasID = 2,
                            Bevetel = 18000,
                            Cim = "Szeged, Kossuth utca 12.",
                            Email = "nagy.peter@example.com",
                            EszkozID = 5,
                            FoglalasKezdete = new DateTime(2025, 3, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            FoglalasVege = new DateTime(2025, 3, 21, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            LetrehozasDatum = new DateTime(2025, 3, 18, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            Nev = "Nagy Péter",
                            OraSzam = 36,
                            Status = 1,
                            Telefonszam = "+36209876543"
                        });
                });

            modelBuilder.Entity("SzerszamKolcsonzo.Models.Kategoria", b =>
                {
                    b.Property<int>("KategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KategoriaID"));

                    b.Property<string>("KepUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("KategoriaID");

                    b.HasIndex("Nev")
                        .IsUnique();

                    b.ToTable("Kategoriak");

                    b.HasData(
                        new
                        {
                            KategoriaID = 1,
                            Nev = "kézi szerszámok"
                        },
                        new
                        {
                            KategoriaID = 2,
                            Nev = "mérőműszerek"
                        },
                        new
                        {
                            KategoriaID = 3,
                            Nev = "kerti eszközök"
                        });
                });

            modelBuilder.Entity("SzerszamKolcsonzo.Models.Eszkoz", b =>
                {
                    b.HasOne("SzerszamKolcsonzo.Models.Kategoria", "Kategoria")
                        .WithMany("Eszkozok")
                        .HasForeignKey("KategoriaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategoria");
                });

            modelBuilder.Entity("SzerszamKolcsonzo.Models.Foglalas", b =>
                {
                    b.HasOne("SzerszamKolcsonzo.Models.Eszkoz", "Eszkoz")
                        .WithMany("Foglalasok")
                        .HasForeignKey("EszkozID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eszkoz");
                });

            modelBuilder.Entity("SzerszamKolcsonzo.Models.Eszkoz", b =>
                {
                    b.Navigation("Foglalasok");
                });

            modelBuilder.Entity("SzerszamKolcsonzo.Models.Kategoria", b =>
                {
                    b.Navigation("Eszkozok");
                });
#pragma warning restore 612, 618
        }
    }
}
